myproject/regschool/models.py
################################################################
#### CREATE THE NECCESSARY IMPORTS FOR THE REGSCHOOL MODEL #####
################################################################

from myproject import db

################################################
#### CREATE THE MODELS FOR THE REGSCHOOL #######
################################################

class RegisterSchool(db.Model):
    __tablename__ = "schools"

    id = db.Column(db.Integer, primary_key = True)
    schoolname = db.Column(db.Text(128))
    #teammembers = db.Column(db.Text(128))
    coachname = db.Column(db.Text(128))
    registrationfee = db.Column(db.Integer)
    regteam = db.relationship("RegTeam", backref = "regschool", uselist = False)


    def __init__(self, schoolname, coachname, registrationfee):
        self.schoolname = schoolname
        #self.teammembers = teammembers
        self.coachname = coachname
        self.registrationfee = registrationfee

    def __repr__(self):
        if self.regteam:
            return f"The team name is {self.schoolname} and our coach is {self.coachname} and we have paid a registration fee of {self.registrationfee}."
         # The team members include\ {self.teammembers}


class RegTeam(db.Model):
    __tablename__ = "members"

    id = db.Column(db.Integer, primary_key = True)
    member = db.Column(db.Text(128))
    sch_id = db.Column(db.Integer, db.ForeignKey("schools.id"))

    def __init__(self, member, sch_id):
        self.member = member
        self.sch_id = sch_id

    def __repr__(self):
        return f"Name: {self.member} || Team: {self.sch_id}"

myproject/regschool/forms.py
#################################################################
#### CREATE THE NECCESSARY IMPORTS FOR THE REGSCHOOL FORMS ######
#################################################################

from flask_wtf import FlaskForm
from wtforms import StringField, IntegerField, SubmitField, FloatField
from wtforms.validators import DataRequired
from wtforms.validators import ValidationError

###############################################
#### CREATE THE FORMS FOR THE REGSCHOOL #######
###############################################

class RegSchoolForm(FlaskForm):
    schoolname = StringField("Enter the name of the school: ", validators = [DataRequired("Please ensure to enter the correct information")])
    coachname = StringField("Enter the name of the head Coach: ", validators = [DataRequired("Please ensure to enter the correct information")])
    registrationfee = FloatField("Enter the registration amount: ", validators = [DataRequired("Please ensure to enter the correct information")])
    submit = SubmitField("REGISTER")

    def check_school(self, field):
        if RegisterSchool.query.filter_by(schoolname = field.data).first():
            raise ValidationError("The school has already been registered")

class RegMemberForm(FlaskForm):
    member = StringField("Enter the name of the player: ")
    sch_id = IntegerField("ID of the school: ")
    submit = SubmitField("ENTER")

myproject/__init__.py
###########################################################
#### CREATE THE NECCESSARY IMPORTS FOR THE INIT FILE ######
###########################################################

import os
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate

#############################################
#### CREATE THE DATABASE CONNECTION #########
#############################################

app = Flask(__name__)

basedir = os.path.abspath(os.path.dirname(__file__))

app.config["SECRET_KEY"] = "AAaakkJL123##$$%&@%)*(*!@#$%^&*)waMUgiKajoseNgeth@#$E"
app.config["SQLALCHEMY_DATABASE_URI"] = "sqlite:///" + os.path.join(basedir, "data.sqlite")
app.config["SQLALCHEMY_TRACK_MODIFICATIONS"] = False

db = SQLAlchemy(app)
Migrate(app, db)


####################################################
#### IMPORT THE BLUEPRINTS #######
####################################################
from myproject.regschool.views import regschool_blueprints


####################################
#### REGISTER THE BLUEPRINTS ######
####################################

app.register_blueprint(regschool_blueprints, url_prefix = "/regschool")

myproject/regschool/views.py
##################################################################
##### CREATE THE NECCESSARY IMPORTS FOR THE REGSCHOOL VIEWS ######
##################################################################

from flask import Blueprint, render_template, request, flash, redirect, url_for
from myproject import db
from myproject.regschool.forms import RegSchoolForm, RegMemberForm
from myproject.regschool.models import RegisterSchool, RegTeam

###################################################
### CREATE THE VIEWS FOR THE REGSCHOOL ############
###################################################

regschool_blueprints = Blueprint("regschool", __name__, template_folder = "templates/regschool")

@regschool_blueprints.route("/regschool", methods = ["GET", "POST"])
def regschool():
    form = RegSchoolForm()
    if form.validate_on_submit():
        schoolname = form.schoolname.data
        coachname = form.coachname.data
        registrationfee = form.registrationfee.data

        new_school = RegisterSchool(schoolname, coachname, registrationfee)
        db.session.add(new_school)
        db.session.commit()

        return redirect (url_for("thankyou"))

    return render_template("regschool.html", form = form)

@regschool_blueprints.route("/regmembers", methods = ["GET", "POST"])
def regmembers():
    form = RegMemberForm()
    if form.validate_on_submit():
        member = form.member.data
        sch_id = form.sch_id.data
        new_member = RegTeam(member, sch_id)
        db.session.add(new_member)
        db.session.commit()

        return redirect(url_for("thankyou"))

    return render_template("regschool.html", form = form)

myproject/templates/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </head>
  <body>

    <nav class="navbar navbar-expand-lg navbar-light bg-light">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
    <div class="navbar-nav">
      <a class="nav-item nav-link active" href="{{ url_for('index') }}">Home <span class="sr-only">(current)</span></a>
      <a class="nav-item nav-link" href="{{ url_for('regschool.regschool') }}">Register School</a>
      <a class="nav-item nav-link" href="{{ url_for('regschool.regmembers')}}">Regiter Players</a>
    </div>
  </div>
</nav>

    {% block content%}

    {% endblock %}

  </body>
</html>

myproject/templates/home.html
{% extends "base.html"%}
{% block content %}

{% endblock %}